//[cpe_app]
//10.0.1.25 ansible_user=ec2-user ansible_ssh_private_key_file=/tmp/ansible-key.pem


[cpe_app]
${EC2_INSTANCE_ID} ansible_connection=amazon.aws.ssm ansible_python_interpreter=/usr/bin/python3



