---
- name: Deploy Accumulator Application
  hosts: all
  become: yes

  collections:
    - amazon.aws

  vars:
    ansible_connection: aws_ssm
    ansible_python_interpreter: /usr/bin/python3


  vars:
    ansible_connection: amazon.aws.ssm
    ansible_python_interpreter: /usr/bin/python3

    db_endpoint_1: "{{ lookup('env', 'DB_ENDPOINT_1') }}"
    db_endpoint_2: "{{ lookup('env', 'DB_ENDPOINT_2') }}"
    db_name: "{{ lookup('env', 'DB_NAME') }}"
    db_port: "{{ lookup('env', 'DB_PORT') }}"

  tasks:
    - name: Ensure deployment directory exists
      file:
        path: /opt/accumulator
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Copy JAR to server
      copy:
        src: accumulator-*.jar
        dest: /opt/accumulator/accumulator.jar
        mode: '0755'

    - name: Template DB config
      template:
        src: templates/db_active.j2
        dest: /opt/accumulator/db_active.conf
        mode: '0644'

    - name: Restart accumulator service
      systemd:
        name: accumulator
        state: restarted
        enabled: yes
